### ISSUE TITLE
Additional options missing

### ISSUE THREAD

**Issue by intrastella** [everburstSun/dash-molstar#12]
We would like to use your library but I cannot change any other options like colors etc. Is it possible to change the same options as in the front end when using Molstar?

Thank in advance.

**Comment by everburstSun** [comment]
Currently it is only possible to specify the representations through this library. Other options haven't been implemented. But you still can toggle the control panel of molstar to change all the settings in the front end.

**Comment by intrastella** [comment]
I see. Thanks for your fast reply.

You wrote about the layout parameter in dash_molstar.MolstarViewer:
- layout (dict; optional):
    The layout of the molstar viewer. Determining what controls to be
    displayed.   The layout is not allowed to be changed once the
    component has been initialized.

Could you specify which options are available?

**Comment by everburstSun** [comment]
> I see. Thanks for your fast reply.
> 
> You wrote about the layout parameter in dash_molstar.MolstarViewer:
> 
> * layout (dict; optional):
>   The layout of the molstar viewer. Determining what controls to be
>   displayed.   The layout is not allowed to be changed once the
>   component has been initialized.
> 
> Could you specify which options are available?

You can check the [documentation](https://github.com/everburstSun/dash-molstar/blob/main/DOCUMENTATION.md#parameters) for available options of `layout`. Currently there is no official explanations on these options but I think it is easy to infer the usage through their names.



> And is it possible t save the changed molstar setting from the user and load them? I have multiple pages and would like to keep the users' settings.

Absolutely yes. What you need to do is to export your adjusted structures to a molstar session file (.molx) and load it with the method `parse_url(url, mol=False)`. An example can be found here in the [example](https://github.com/everburstSun/dash-molstar-example/blob/main/pages/home.py) repository.

**Comment by intrastella** [comment]
Thanks a lot :)
that is very helpful!

**Comment by intrastella** [comment]
We have one more question: we want to save sessions / state automatically on specific triggers. Is there a function in your lib or from molstar that executes the saving of the session into a specific directory?

**Comment by everburstSun** [comment]
I think there is not such a function in the rcsb fork of molstar, and I didn't implement it neither.
