### ISSUE TITLE
select residue with insertion code 

### ISSUE THREAD

**Issue by biochunan** [everburstSun/dash-molstar#4]
Hi, thanks for the amazing work, and it's been very helpful. 

Is it possible to select residue with an insertion code? For example a residue index of 100A. I was using this function. 
```
R1 = molstar_helper.get_targets(chain='H', residue='100A')
```
this selected all residues with residue index 100 regardless of insertion code, i.e. this selected 100A, 100B, 100C, ...

**Comment by everburstSun** [comment]
Hi, the latest v1.1.0 release has supported selecting residues with insertion code. You may upload the package with pip and try the new features.
